### ISSUE TITLE
raw_crops_rgb_and_flow.npy

### ISSUE THREAD

**Issue by shi123abc** [muslim-adedamola/video-based-action-recognition#1]
Dear Muslim Alaran,

I'm conducting research on action recognition using the UCF sports dataset. In your code, you mentioned loading multiple arrays from a file called raw_crops_rgb_and_flow.npy. Would it be possible for you to share this data file, or provide information on how it was generated? Access to this file would help me replicate important aspects of your work.

I understand the data may be large, so any guidance you could offer would be greatly appreciated. My goal is to further scientific progress in this area through open collaboration. Please let me know if there is any way I can access this resource, or alternatively learn your process for creating it.

Thank you in advance for your consideration. I hope my request is reasonable and does not cause undue burden. Please feel free to respond or ask any questions.

**Comment by muslim-adedamola** [comment]
Hi
Yes, of course, I can share the file with you. It is about 3.77gig. Find the attached file [here](https://drive.google.com/file/d/1y2QDdtk4zWtuSCGDRhmk9VgbPS_qmQQs/view?usp=drive_link).

**Comment by shi123abc** [comment]
Dear Muslim Alaran,

I hope this message finds you well. I am currently conducting research in action recognition .

I sincerely appreciate any guidance or assistance you might provide. My aim is to contribute collaboratively to the progression of knowledge in this field. Therefore, if it's possible, I would greatly appreciate access to this resource or any insights into the process used to create it.

Thank you in advance for considering my request. I sincerely hope that my inquiry is not burdensome. Your expertise and insights would be invaluable to my research.

Could you kindly provide your email address for further communication? I can be reached at 863380699@qq.com.

Looking forward to your positive response and any guidance you might offer. Please feel free to ask any questions or raise concerns.
